version: '3.7'

services:

  nginx:
    image: nginx:1.17-alpine
    container_name: jtsu-nginx
    restart: unless-stopped
    working_dir: /app
    ports:
      - 20080:80 # frontend
      - 20081:81 # backend
      - 20082:82 # storage
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - db

  php-fpm:
    build: docker/php-fpm
    restart: unless-stopped
    container_name: jtsu-php
    working_dir: /app
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 33061:3306
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql
      - ./docker/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: jtsu
      MYSQL_USER: ROOT_USER
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
