<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LAST <span>ANNOUNCEMENT</span>' => 'SO`NGGI <span>E`LONLAR</span>',
    'LAST <span>CONTESTS</span>' => 'SO`NGGI <span>TANLOVLAR</span>',
    'Categories' => 'Kategoriyalar',
    'Contact us' => 'Biz bilan bog`laning',
    'Developed by <a href="{url}">PROACTIVE MEDIA</a>' => '<a href="{url}">PROACTIVE MEDIA</a> tomonidan ishlan chiqildi',
    'Email' => 'Email',
    'Faculties' => 'Fakultetlar',
    'ID' => 'ID',
    'Interactive services' => 'Interaktiv xizmatlar',
    'LAST <span>NEWS</span>' => 'SO`NGGI <span>YANGILIKLAR</span>',
    'Name' => 'Ismi',
    'Search' => 'Qidirish',
    'Nothing found' => 'Hech narsa topilmadi',
    'Partners' => 'Hamkorlar',
    'Phone' => 'Telefon raqami',
    'Phone/Email' => 'Telefon raqami/Email',
    'Photo gallery' => 'Foto galereya',
    'Recent news' => 'So`nggi yangiliklar',
    'Send' => 'Jo`natish',
    'Show more' => 'Barchasi',
    'Site map' => 'Sayt xaritasi',
    'State symbols' => 'Davlat ramzlari',
    'Go to platform' => 'Platformaga o`tish',
    'Text' => 'Matn',
    'Contact' => 'Bog`lanish',
    'UZBEK STATE UNIVERSITY OF <br>PHYSICAL CULTURE AND SPORT' => 'O`ZBEKISTON DAVLAT JISMONIY <br>TARBIYA VA SPORT UNIVERSITETI',
    'Search results' => 'Qidiruv natijalari',
    'Uzbek state university of physical culture and sport' => 'O`zbekiston davlat jismoniy tarbiya va sport universiteti',
    'Special abilities' => 'Maxsus imkoniyatlar',
    'When using the materials on the site in full or in part, it is necessary to refer to this resource' => 'Saytdagi materiallardan to`liq yoki qisman foydalanilganda, ushbu resursga havola etilishi shart',
    'Join' => 'Ulanish',
    'Join to our Telegram channel' => 'Telegramdagi kanalimizga ulaning',
    'Announcement' => 'E`lonlar',
    'Contests' => 'Tanlovlar',
    'Honorary teachers' => 'Faxriy o`qituvchilar',
    'Cathedras' => 'Kafedralar',
    'Reception times' =>'Qabul vaqtlari',
    'Phone number' => 'Telefon raqam',
    'Contact Information' => 'Bog`lanish uchun ma`lumot',
    'Location' => 'Manzil',
    'Call Us' => 'Bizga qo`ng`iroq qiling',
    'Mail Us' => 'Bizga xabar yuboring',
    'Enter Your Name' => 'Ismingizni kiriting',
    'Enter Your Phone' => 'Telefoningizni kiriting',
    'Enter Your Message...' => 'Xabaringizni kiriting ...',
    'Next' => 'Keyingi',
    'Previous' => 'Oldingi',
    'Last News' => 'So`nggi yangiliklar',
    'Previous site' => 'Avvalgi sayt',
    'Full Name' => 'To`liq ismi',
    'Message' => 'Xabar',
    'Email or phone' => 'Elektron pochta yoki telefon',
    'Created At' => 'Yaratilgan vaqti',
    'No data found' => 'Hech qanday ma\'lumot topilmadi',
    'Please confirm that you are not a bot.' => 'Iltimos, bot emasligingizni tasdiqlang.',
    'An error occurred.' => 'Произошла ошибка.',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Biz bilan bog\'langaningiz uchun tashakkur. Biz sizga imkon qadar tezroq javob beramiz.'



]; 
