<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LAST <span>ANNOUNCEMENT</span>' => 'ПОСЛЕДНИЕ <span>ОБЪЯВЛЕНИЯ</span>',
    'LAST <span>CONTESTS</span>' => 'ПОСЛЕДНИЕ <span>КОНКУРСЫ</span>',
    'Categories' => 'Категории',
    'Contact us' => 'Связаться с нами',
    'Developed by <a href="{url}">PROACTIVE MEDIA</a>' => 'Разработан в <a href="{url}">PROACTIVE MEDIA</a>',
    'Email' => 'Эл. адрес',
    'Faculties' => 'Факультеты',
    'ID' => 'ID',
    'Interactive services' => 'Интерактивные услуги',
    'LAST <span>NEWS</span>' => 'ПОСЛЕДНИЕ <span>НОВОСТИ</span>',
    'Name' => 'Имя',
    'Search' => 'Поиск',
    'Nothing found' => 'Ничего не найдено',
    'UZBEK STATE UNIVERSITY OF <br>PHYSICAL CULTURE AND SPORT' => 'УЗБЕКСКИЙ ГОСУДАРСТВЕННЫЙ УНИВЕРСИТЕТ <br>ФИЗИЧЕСКОЙ КУЛЬТУРЫ И СПОРТА',
    'Partners' => 'Партнеры',
    'Phone' => 'Телефон',
    'Phone/Email' => 'Телефон / Электронная почта',
    'Photo gallery' => 'Фото галерея',
    'Recent news' => 'Последные новости',
    'Send' => 'Отправить',
    'Show more' => 'Показать все',
    'Site map' => 'Карта сайта',
    'State symbols' => 'Государственные символы',
    'Go to platform' => 'Переход на платформу',
    'Text' => 'Текст',
    'Contact' => 'Контакт',
    'Search results' => 'Результаты поиска',
    'Uzbek state university of physical culture and sport' => 'Узбекский государственный университет физической культуры и спорта',
    'Special abilities' => 'Специальные возможности',
    'When using the materials on the site in full or in part, it is necessary to refer to this resource' => 'При использовании материалов сайта полностью или частично необходимо обращаться к этому ресурсу',
    'Join' => 'Присоединиться',
    'Join to our Telegram channel' => 'Присоединяйтесь к нашему Telegram каналу',
    'Announcement' => 'Объявление',
    'Contests' => 'Конкурсы',
    'Honorary teachers' => 'Почетные учители',
    'Cathedras' => 'Kафедры',
    'Reception times' => 'Время приема',
    'Phone number' => 'Телефонный номер',
    'Contact Information' => 'Контакты',
    'Location' => 'Место расположения',
    'Call Us' => 'Позвоните нам',
    'Mail Us' => 'Напишите нам',
    'Enter Your Name' => 'Введите ваше имя',
    'Enter Your Phone' => 'Введите свой телефон',
    'Enter Your Message...' => 'Введите ваше сообщение...',
    'Next' => 'Следующий',
    'Previous' => 'Предыдущий',
    'Last News' => 'Последние новости',
    'Previous site' => 'Предыдущий сайт',
    'Full Name' => 'ФИО',
    'Email or phone' => 'По электронной почте или телефону',
    'Message' => 'Сообщение',
    'No data found' => 'Данные не найдены',
    'Please confirm that you are not a bot.' => 'Подтвердите, что вы не бот.',
    'An error occurred.' => 'Произошла ошибка.',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Благодарим Вас за обращение к нам. Мы ответим вам как можно скорее.'
];
